
/* Drop Indexes */

DROP INDEX TB_CODE_PK;



/* Drop Tables */

DROP TABLE ESHOP.TB_CART CASCADE CONSTRAINTS;
DROP TABLE ESHOP.TB_COM_CODE CASCADE CONSTRAINTS;
DROP TABLE ESHOP.TB_MARK CASCADE CONSTRAINTS;
DROP TABLE ESHOP.TB_REPLY CASCADE CONSTRAINTS;
DROP TABLE ESHOP.TB_SELL CASCADE CONSTRAINTS;
DROP TABLE ESHOP.TB_COM_USER CASCADE CONSTRAINTS;
DROP TABLE ESHOP.TB_POST CASCADE CONSTRAINTS;
DROP TABLE ESHOP.TB_PRODUCT CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE ESHOP.CART_SEQ;
DROP SEQUENCE ESHOP.PRODUCT_SEQ;
DROP SEQUENCE ESHOP.SELL_SEQ;
DROP SEQUENCE ESHOP.USER_SEQ;




/* Create Sequences */

CREATE SEQUENCE ESHOP.CART_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;
CREATE SEQUENCE ESHOP.PRODUCT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 61 CACHE 20;
CREATE SEQUENCE ESHOP.SELL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;
CREATE SEQUENCE ESHOP.USER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 21 CACHE 20;



/* Create Tables */

CREATE TABLE ESHOP.TB_CART
(
	CART_CODE varchar2(20 char) NOT NULL,
	PRODUCT_CODE varchar2(20 char),
	USER_CODE varchar2(20 char),
	CART_PRICE number,
	CART_COUNT number,
	CART_DATE varchar2(30 char),
	CONSTRAINT TB_CART_PK PRIMARY KEY (CART_CODE)
);


CREATE TABLE ESHOP.TB_COM_CODE
(
	COMM_TY_CD varchar2(10 char) NOT NULL,
	COMM_CD varchar2(20 char) NOT NULL,
	COMM_CD_NM varchar2(30 char),
	CONSTRAINT TB_CODE_PK PRIMARY KEY (COMM_TY_CD, COMM_CD)
);


CREATE TABLE ESHOP.TB_COM_USER
(
	USER_CODE varchar2(20 char) NOT NULL,
	ID varchar2(20 char),
	PW varchar2(20 char),
	EMAIL varchar2(50 char),
	USER_IMAGE varchar2(100 char),
	NAME varchar2(20 char),
	BIRTH varchar2(20 char),
	POST_NUM varchar2(20 char),
	PHONE_CD varchar2(2 char),
	PHONE_NUM varchar2(20 char),
	ADDRESS varchar2(100 char),
	ENT_DATE varchar2(30 char),
	GRADE varchar2(1 char) DEFAULT '''M''',
	CONSTRAINT TB_COM_USER_PK PRIMARY KEY (USER_CODE)
);


CREATE TABLE ESHOP.TB_MARK
(
	PRODUCT_CODE varchar2(20 char) NOT NULL,
	USER_CODE varchar2(20 char) NOT NULL,
	MARK_RATING number,
	CONSTRAINT TB_MARK_PK PRIMARY KEY (PRODUCT_CODE, USER_CODE)
);


CREATE TABLE ESHOP.TB_POST
(
	ZIPCODE varchar2(10 char),
	SIDO varchar2(50 char),
	GUGUN varchar2(100 char),
	DONG varchar2(100 char),
	BUNJI varchar2(50 char),
	SEQ number NOT NULL,
	CONSTRAINT SYS_C0011152 PRIMARY KEY (SEQ)
);


CREATE TABLE ESHOP.TB_PRODUCT
(
	PRODUCT_CODE varchar2(20 char) NOT NULL,
	PRODUCT_IMAGE varchar2(70 char),
	PRODUCT_NAME varchar2(200 char),
	PRODUCT_UNIT_PRICE number,
	PRODUCT_COUNT number,
	PRODUCT_CATEGORY_CD varchar2(20 char),
	PRODUCT_REG_DATE varchar2(20 char),
	CONSTRAINT TB_PRODUCT_PK PRIMARY KEY (PRODUCT_CODE)
);


CREATE TABLE ESHOP.TB_REPLY
(
	PRODUCT_CODE varchar2(20 char) NOT NULL,
	USER_CODE varchar2(20 char) NOT NULL,
	USER_REPLY_NO number(3,0) NOT NULL,
	USER_REPLY varchar2(1000 char),
	REPLY_DATE varchar2(30 char),
	CONSTRAINT TB_REPLY_PK PRIMARY KEY (PRODUCT_CODE, USER_CODE, USER_REPLY_NO)
);


CREATE TABLE ESHOP.TB_SELL
(
	SELL_CODE varchar2(20 char) NOT NULL,
	PRODUCT_CODE varchar2(20 char),
	USER_CODE varchar2(20 char),
	SELL_PRICE number,
	SELL_COUNT number,
	SELL_YN varchar2(1 char) DEFAULT '''N''',
	SELL_DATE varchar2(30 char),
	CONSTRAINT TB_SELL_PK PRIMARY KEY (SELL_CODE)
);



/* Create Foreign Keys */

ALTER TABLE ESHOP.TB_CART
	ADD CONSTRAINT TB_CART_FK_USER FOREIGN KEY (USER_CODE)
	REFERENCES ESHOP.TB_COM_USER (USER_CODE)
;


ALTER TABLE ESHOP.TB_MARK
	ADD CONSTRAINT TB_MARK_FK_USER FOREIGN KEY (USER_CODE)
	REFERENCES ESHOP.TB_COM_USER (USER_CODE)
;


ALTER TABLE ESHOP.TB_REPLY
	ADD CONSTRAINT TB_REPLY_FK_USER FOREIGN KEY (USER_CODE)
	REFERENCES ESHOP.TB_COM_USER (USER_CODE)
;


ALTER TABLE ESHOP.TB_SELL
	ADD CONSTRAINT TB_SELL_FK_USER FOREIGN KEY (USER_CODE)
	REFERENCES ESHOP.TB_COM_USER (USER_CODE)
;


ALTER TABLE ESHOP.TB_CART
	ADD CONSTRAINT TB_CART_FK_PRODUCT FOREIGN KEY (PRODUCT_CODE)
	REFERENCES ESHOP.TB_PRODUCT (PRODUCT_CODE)
;


ALTER TABLE ESHOP.TB_MARK
	ADD CONSTRAINT TB_MARK_FK_PRODUCT FOREIGN KEY (PRODUCT_CODE)
	REFERENCES ESHOP.TB_PRODUCT (PRODUCT_CODE)
;


ALTER TABLE ESHOP.TB_REPLY
	ADD CONSTRAINT TB_REPLY_FK_PRODUCT FOREIGN KEY (PRODUCT_CODE)
	REFERENCES ESHOP.TB_PRODUCT (PRODUCT_CODE)
;


ALTER TABLE ESHOP.TB_SELL
	ADD CONSTRAINT TB_SELL_FK_PRODUCT FOREIGN KEY (PRODUCT_CODE)
	REFERENCES ESHOP.TB_PRODUCT (PRODUCT_CODE)
;



/* Create Indexes */

CREATE UNIQUE INDEX TB_CODE_PK ON ESHOP.TB_COM_CODE (COMM_TY_CD, COMM_CD);



